//! SC-W5-079 – Shared event correlation ids for cross-contract tracing.
//!
//! This module provides a `CorrelationId` type and associated functions for
//! propagating a shared correlation identifier across contract boundaries.
//! Backend consumers use the correlation ID to trace a single workflow (e.g.,
//! an SLA calculation that triggers a payment settlement) across events
//! emitted by multiple contracts.
//!
//! # Design
//!
//! A `CorrelationId` is a `u64` value that is:
//! - Generated by the entry-point contract (usually the SLA calculator)
//! - Passed as an argument to downstream contract calls
//! - Emitted in every event payload that is part of the same logical workflow
//!
//! # Integration
//!
//! The SLA calculator's `calculate_sla` function generates a correlation ID
//! from the outage_id and ledger sequence, then includes it in the
//! `set_int` event payload and any downstream calls.
//!
//! Downstream contracts (payment escrow, settlement) accept the correlation
//! ID as a parameter and include it in their own events.

use soroban_sdk::{symbol_short, Env, Symbol};

/// Opaque correlation identifier for tracing workflows across contracts.
///
/// A `CorrelationId` is a `u64` that uniquely identifies a logical workflow
/// spanning one or more contract calls.  It is deterministic for a given
/// (outage_id, ledger_sequence) pair so that backends can re-derive it.
pub type CorrelationId = u64;

/// Event topic symbol for the correlation ID in cross-contract events.
pub const CORRELATION_TOPIC: Symbol = symbol_short!("corr_id");

/// Generates a deterministic correlation ID from the current ledger sequence.
///
/// Uses a simple FNV-1a hash of the ledger sequence to produce a unique
/// trace identifier per ledger. The `_outage_id` parameter is reserved for
/// future use (Symbol bytes are not directly accessible in SDK 21.x).
pub fn generate_correlation_id(
    _env: &Env,
    _outage_id: &Symbol,
    ledger_sequence: u32,
) -> CorrelationId {
    // Deterministic hash: use ledger sequence with FNV-1a mixing for temporal uniqueness
    // (Outage_id bytes are not directly accessible in Soroban SDK 21.x without Symbol::to_string)
    let mut hash: u64 = 0xcbf29ce484222325; // FNV-1a offset basis
    hash ^= (ledger_sequence as u64) << 32 | ledger_sequence as u64;
    hash = hash.wrapping_mul(0x100000001b3); // FNV-1a prime
    hash
}
/// Generates a cross-contract event topic tuple that includes the
/// correlation ID as the final topic element.
///
/// Topic layout:
///   topic[0] = event name (e.g., "sla_calc")
///   topic[1] = event version ("v1")
///   topic[2] = event-specific context (e.g., severity)
///   topic[3] = correlation_id (as a u64-compatible value)
pub fn correlation_event_topics(
    event_name: Symbol,
    event_version: Symbol,
    context: Symbol,
    correlation_id: CorrelationId,
) -> (Symbol, Symbol, Symbol, u64) {
    (event_name, event_version, context, correlation_id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use soroban_sdk::Env;

    #[test]
    fn test_correlation_id_is_deterministic() {
        let env = Env::default();
        let outage = Symbol::new(&env, "OUT001");
        let id1 = generate_correlation_id(&env, &outage, 42);
        let id2 = generate_correlation_id(&env, &outage, 42);
        assert_eq!(id1, id2);
    }

    #[test]
    fn test_correlation_id_changes_with_ledger_sequence() {
        let env = Env::default();
        let outage = Symbol::new(&env, "OUT001");
        // Different ledger sequences must produce different IDs
        let id_seq1 = generate_correlation_id(&env, &outage, 42);
        let id_seq2 = generate_correlation_id(&env, &outage, 100);
        assert_ne!(id_seq1, id_seq2);
    }

    #[test]
    fn test_correlation_id_is_non_zero() {
        let env = Env::default();
        let id = generate_correlation_id(&env, &Symbol::new(&env, "OUT001"), 1);
        assert_ne!(id, 0, "Correlation ID should not be zero");
    }

    #[test]
    fn test_correlation_id_distinct_ledger_sequences() {
        let env = Env::default();
        let outage = Symbol::new(&env, "OUT001");
        // Verify that different ledger sequences produce distinct outputs
        let id1 = generate_correlation_id(&env, &outage, 1);
        let id2 = generate_correlation_id(&env, &outage, 2);
        let id3 = generate_correlation_id(&env, &outage, 3);
        assert_ne!(id1, id2);
        assert_ne!(id2, id3);
        assert_ne!(id1, id3);
    }

    #[test]
    fn test_correlation_event_topics_structure() {
        let topics = correlation_event_topics(
            symbol_short!("sla_calc"),
            symbol_short!("v1"),
            symbol_short!("critical"),
            42,
        );
        assert_eq!(topics.0, symbol_short!("sla_calc"));
        assert_eq!(topics.1, symbol_short!("v1"));
        assert_eq!(topics.2, symbol_short!("critical"));
        assert_eq!(topics.3, 42u64);
    }

    #[test]
    fn test_correlation_id_long_outage_id() {
        let env = Env::default();
        let long_outage = Symbol::new(&env, "INC_2024_03_15_ABCDEF123456");
        let id = generate_correlation_id(&env, &long_outage, 99);
        assert_ne!(id, 0);
    }

    #[test]
    fn test_correlation_id_empty_symbol_still_hashes() {
        let env = Env::default();
        // Edge case: very short symbol
        let short = Symbol::new(&env, "X");
        let id = generate_correlation_id(&env, &short, 1);
        assert_ne!(id, 0);
    }

    #[test]
    fn test_correlation_topic_has_correct_type() {
        let topics = correlation_event_topics(
            symbol_short!("set_int"),
            symbol_short!("v1"),
            symbol_short!("critical"),
            12345,
        );
        assert_eq!(topics.3, 12345u64);
    }
}
